# примеры API-запросов
###
@baseUrl = http://localhost:8000/api

###
# получение датчиков
GET http://localhost:8000/api/sensors/
Content-Type: application/json

###

# создание датчика
POST http://localhost:8000/api/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик на кухне за холодильником"
}

###

# обновление датчика
PATCH http://localhost:8000/api/sensors/3/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST http://localhost:8000/api/measurements/
Content-Type: application/json

{
  "sensor": 4,
  "temperature": 22.3
}

###

# получение информации по датчику
GET http://localhost:8000/api/sensors/1/
Content-Type: application/json
